### PR TITLE
Add Web App

### PR DESCRIPTION
**Pull request by gibbiemonster**
Creates a cool looking web app with Primer CSS

Will be hosted via GitHub Pages.

### CODE REVIEW

**Comment by zNotChill** [comment]
This project would not be possible with GitHub pages due to Backend issues

**Comment by gibbiemonster** [comment]
We can go ahead and use Netlify - or maybe vercel.

Azure Static Web Apps is another great option

**Comment by zNotChill** [comment]
bro i am broke

**Comment by gibbiemonster** [comment]
Discussed elsewhere. Please merge.

**Pull request merged**
